## library() calls go here
library(conflicted)
library(dotenv)
library(drake)
# data management
library(haven)
library(janitor)
library(magrittr)
library(labelled)
# data analysis
library(tidyverse)
library(tidymodels)
library(tidyselect)
library(xgboost)
library(xgboost.surv)
library(riskRegression)
library(survival)
library(ranger)
library(rms)
library(Hmisc)
library(survminer)
library(cmprsk)
# reporting
library(tblStrings)
library(broom)
library(officer)
library(glue)
library(flextable)
library(devEMF)
library(magick)
library(paletteer)
library(patchwork)
library(tibbleOne)
library(naniar)

conflict_prefer("font", "flextable")
conflict_prefer("roc",       "pROC")
conflict_prefer("filter",    "dplyr")
conflict_prefer("slice",     "dplyr")
conflict_prefer('summarise', 'dplyr')
conflict_prefer('summarize', 'dplyr')
conflict_prefer("gather",    "tidyr")
conflict_prefer("set_names", "purrr")
conflict_prefer("matches",   "tidyselect")
